### ISSUE TITLE
Use webhooks to send events to PCBridge

### ISSUE THREAD

**Issue by andyksaw** [projectcitybuild/web#582]
**Is your feature request related to a problem? Please describe.**
Currently users have to run `/sync finish` in-game manually to have their rank synced the first time.

Using websockets, we should be able to establish a connection to the PCBridge plugin and have syncing run automatically after they finish linking their account

**Comment by freddyheppell** [comment]
I think this would end up being a massive pain to implement at both ends (particularly on the PHP side..), and also possibly overkill since we don't really need persistent bidirectional communication. 

I think our best option is probably for PCBridge to start a Jetty (or the nice Kotlin ecosystem equivalent I'm sure exists) and then have the site fire HTTP requests at it. Should be able to make that run through Laravel's notification system too.
